# Generated by Django 5.1 on 2025-09-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_class_class_code_class_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
