# Generated by Django 5.1 on 2025-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_alter_loginhistory_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
