# Generated by Django 5.1 on 2025-10-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classroom.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='class',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='classes', to='classroom.tag', verbose_name='Tags'),
        ),
    ]
