# Generated by Django 5.1 on 2025-11-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_class_category_class_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendance_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance End Time'),
        ),
        migrations.AddField(
            model_name='session',
            name='attendance_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance Start Time'),
        ),
        migrations.AddField(
            model_name='session',
            name='auto_attendance',
            field=models.BooleanField(default=False, verbose_name='Automatic Attendance'),
        ),
    ]
