# Generated by Django 5.1 on 2025-10-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_announcement_type_loginhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_time'], 'verbose_name': 'Login History', 'verbose_name_plural': 'Login Histories'},
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='status',
        ),
    ]
