# Generated by Django 5.1 on 2025-10-04 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
