# Generated by Django 5.1 on 2025-10-04 09:07

from django.db import migrations
import uuid


def generate_unique_session_ids(apps, schema_editor):
    """Generate unique session_id for existing LoginHistory records"""
    LoginHistory = apps.get_model('classroom', 'LoginHistory')
    
    # Update each record with a unique UUID
    for record in LoginHistory.objects.all():
        record.session_id = uuid.uuid4()
        record.save(update_fields=['session_id'])
    
    print(f"✓ Generated unique session_ids for {LoginHistory.objects.count()} records")


def reverse_func(apps, schema_editor):
    """Reverse migration - set all session_ids to None"""
    LoginHistory = apps.get_model('classroom', 'LoginHistory')
    LoginHistory.objects.all().update(session_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_loginhistory_session_id'),
    ]

    operations = [
        migrations.RunPython(generate_unique_session_ids, reverse_func),
    ]
