# Generated by Django 5.1 on 2025-10-04 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_populate_session_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
